from crosstabs.tableManipulations import stackColumns


profile = TableAxis({
  "Name": "ProfileReportTest",
  "Version" : "1",
  "Elements": [
    { "ElementText": ["Dashboard Attribute", "Refresh Period", "Start Date"], "Condition": "2.1.weeklyView|*|date",
      "Operation": "lambda x: sorted(x)[0]", "CellFormatting" : {"font": {"bold": "False"}, "alignment": {"horizontal":"right"}} },
    { "ElementText": ["Dashboard Attribute", "Refresh Period", "End Date"], "Condition": "2.1.weeklyView|*|date",
      "Operation": "lambda x: sorted(x)[-1]", "CellFormatting" : {"font": {"bold": "False"}, "alignment": {"horizontal":"right"}} },
    { "ElementText": ["Customer", "Total Users", "Count"], "Condition": "totalUsers" },
    { "ElementText": ["Customer", "Total Users in Contract", "Count"], "Condition": "results|contract|items|Contract|count" },
    { "ElementText": ["Customer", "Total Users with Interest", "Count"], "Condition": "results|interests|count" },
    { "ElementText": ["Customer", "Total Addressable Users", "Count"], "Condition": "results|addressable|items|T|count" },
    { "ElementText": ["Demographics", "Gender", "Valid N", "Count"], "Condition": "results|gender|count" },
    { "ElementText": ["Demographics", "Gender", "Male", "Count"], "Condition": "results|gender|items|MALE|count" },
    { "ElementText": ["Demographics", "Gender", "Male", "%"], "Condition": "results|gender|items|MALE|percentage" },
    { "ElementText": ["Demographics", "Gender", "Female", "Count"], "Condition": "results|gender|items|FEMALE|count" },
    { "ElementText": ["Demographics", "Gender", "Female", "%"], "Condition": "results|gender|items|FEMALE|percentage" },
    { "ElementText": ["Demographics", "Gender", "Unknown", "Count"], "Condition": "results|gender|items|UNKNOWN|count" },
    { "ElementText": ["Demographics", "Gender", "Unknown", "%"], "Condition": "results|gender|items|UNKNOWN|percentage" },
    { "ElementText": ["Demographics", "Age", "Valid N", "Count"], "Condition": "results|ageGroup|count" },
    { "ElementText": ["Demographics", "Age", "<18", "Count"], "Condition": "results|ageGroup|items|under 18|count" },
    { "ElementText": ["Demographics", "Age", "<18", "%"], "Condition": "results|ageGroup|items|under 18|percentage" },
    { "ElementText": ["Demographics", "Age", "18 to 24", "Count"], "Condition": "results|ageGroup|items|18 to 24|count" },
    { "ElementText": ["Demographics", "Age", "18 to 24", "%"], "Condition": "results|ageGroup|items|18 to 24|percentage" },
    { "ElementText": ["Demographics", "Age", "25 to 34", "Count"], "Condition": "results|ageGroup|items|25 to 34|count" },
    { "ElementText": ["Demographics", "Age", "25 to 34", "%"], "Condition": "results|ageGroup|items|25 to 34|percentage" },
    { "ElementText": ["Demographics", "Age", "35 to 44", "Count"], "Condition": "results|ageGroup|items|35 to 44|count" },
    { "ElementText": ["Demographics", "Age", "35 to 44", "%"], "Condition": "results|ageGroup|items|35 to 44|percentage" },
    { "ElementText": ["Demographics", "Age", "45 to 54", "Count"], "Condition": "results|ageGroup|items|45 to 54|count" },
    { "ElementText": ["Demographics", "Age", "45 to 54", "%"], "Condition": "results|ageGroup|items|45 to 54|percentage" },
    { "ElementText": ["Demographics", "Age", "55 to 64", "Count"], "Condition": "results|ageGroup|items|55 to 64|count" },
    { "ElementText": ["Demographics", "Age", "55 to 64", "%"], "Condition": "results|ageGroup|items|55 to 64|percentage" },
    { "ElementText": ["Demographics", "Age", "65+", "Count"], "Condition": "results|ageGroup|items|65+|count" },
    { "ElementText": ["Demographics", "Age", "65+", "%"], "Condition": "results|ageGroup|items|65+|percentage" },
    { "ElementText": ["Demographics", "Age", "UNKNOWN", "Count"], "Condition": "results|ageGroup|items|unknown|count" },
    { "ElementText": ["Demographics", "Age", "UNKNOWN", "%"], "Condition": "results|ageGroup|items|unknown|percentage" },
    { "ElementText": ["contract", "Valid N", "Count"], "Condition": "results|contract|count" },
    { "ElementText": ["contract", "In Contract", "Count"], "Condition": "results|contract|items|Contract|count" },
    { "ElementText": ["contract", "In Contract", "%"], "Condition": "results|contract|items|Contract|percentage" },
    { "ElementText": ["contract", "PayAsYouGo", "Count"], "Condition": "results|contract|items|PayAsYouGo|count" },
    { "ElementText": ["contract", "PayAsYouGo", "%"], "Condition": "results|contract|items|PayAsYouGo|percentage" },
    { "ElementText": ["P&L Segment", "Valid N", "Count"], "Condition": "results|pAndLSegments|count" },
    { "ElementText": ["P&L Segment", "PAYM", "Count"], "Condition": "results|pAndLSegments|items|paym|count" },
    { "ElementText": ["P&L Segment", "PAYM", "%"], "Condition": "results|pAndLSegments|items|paym|percentage" },
    { "ElementText": ["P&L Segment", "PAY&GO", "Count"], "Condition": "results|pAndLSegments|items|pay&go|count" },
    { "ElementText": ["P&L Segment", "PAY&GO", "%"], "Condition": "results|pAndLSegments|items|pay&go|percentage" },
    { "ElementText": ["P&L Segment", "Large/Medium Enterprise", "Count"], "Condition": "results|pAndLSegments|items|large medium enterprise|count" },
    { "ElementText": ["P&L Segment", "Large/Medium Enterprise", "%"], "Condition": "results|pAndLSegments|items|large medium enterprise|percentage" },
    { "ElementText": ["P&L Segment", "Small/Medium Enterprise", "Count"], "Condition": "results|pAndLSegments|items|small to medium enterprise|count" },
    { "ElementText": ["P&L Segment", "Small/Medium Enterprise", "%"], "Condition": "results|pAndLSegments|items|small to medium enterprise|percentage" },
    { "ElementText": ["P&L Segment", "Unknown", "Count"], "Condition": "results|pAndLSegments|items|unknown|count" },
    { "ElementText": ["P&L Segment", "Unknown", "%"], "Condition": "results|pAndLSegments|items|unknown|percentage" },
    { "ElementText": ["Contract", "Months to Contract End", "Valid N", "Count"], "Condition": "results|contractEndMonths|count" },
    { "ElementText": ["Contract", "Months to Contract End", "No Contract", "Count"], "Condition": "results|contractEndMonths|items|No contract|count" },
    { "ElementText": ["Contract", "Months to Contract End", "In Last Month", "Count"], "Condition": "results|contractEndMonths|items|In last month|count" },
    { "ElementText": ["Contract", "Months to Contract End", "1-2 months", "Count"], "Condition": "results|contractEndMonths|items|1-2 months|count" },
    { "ElementText": ["Contract", "Months to Contract End", "1-2 months", "%"], "Condition": "results|contractEndMonths|items|1-2 months|percentage" },
    { "ElementText": ["Contract", "Months to Contract End", "2-3 months", "Count"], "Condition": "results|contractEndMonths|items|2-3 months|count" },
    { "ElementText": ["Contract", "Months to Contract End", "2-3 months", "%"], "Condition": "results|contractEndMonths|items|2-3 months|percentage" },
    { "ElementText": ["Contract", "Months to Contract End", "3-6 months", "Count"], "Condition": "results|contractEndMonths|items|3-6 months|count" },
    { "ElementText": ["Contract", "Months to Contract End", "3-6 months", "%"], "Condition": "results|contractEndMonths|items|3-6 months|percentage" },
    { "ElementText": ["Contract", "Months to Contract End", "6-12 months", "Count"], "Condition": "results|contractEndMonths|items|6-12 months|count" },
    { "ElementText": ["Contract", "Months to Contract End", "6-12 months", "%"], "Condition": "results|contractEndMonths|items|6-12 months|percentage" },
    { "ElementText": ["Contract", "Months to Contract End", "All other", "Count"], "Condition": "results|contractEndMonths|items|All other|count" },
    { "ElementText": ["Contract", "Months to Contract End", "All other", "%"], "Condition": "results|contractEndMonths|items|All other|percentage" },
    { "ElementText": ["Contract", "Contract Tenure", "Valid N", "Count"], "Condition": "results|currentTenure|count" },
    { "ElementText": ["Contract", "Contract Tenure", "Current Contract Tenure", "Mean"], "Condition": "results|currentTenure|avg" },
    { "ElementText": ["Contract", "Contract Tenure", "Current Contract Tenure", "Std Dev"], "Condition": "results|currentTenure|std_deviation" },
    { "ElementText": ["Contract", "Contract Duration", "Valid N", "Count"], "Condition": "results|contractTerm|count" },
    { "ElementText": ["Contract", "Contract Duration", "Current Contract Tenure", "Mean"], "Condition": "results|contractTerm|avg" },
    { "ElementText": ["Contract", "Contract Duration", "Current Contract Tenure", "Std Dev"], "Condition": "results|contractTerm|std_deviation" },
    { "ElementText": ["Spend", "Valid N", "Count"], "Condition": "results|spend|count" },
    { "ElementText": ["Spend", "Actual Spend", "Mean"], "Condition": "results|spend|avg" },
    { "ElementText": ["Spend", "Actual Spend", "Std Dev"], "Condition": "results|spend|std_deviation" },
    { "ElementText": ["Usage", "Valid N", "Count"], "Condition": "results|dataSummary|count" },
    { "ElementText": ["Usage", "Actual Data Usage", "Mean"], "Condition": "results|dataSummary|avg" },
    { "ElementText": ["Usage", "Actual Data Usage", "Std Dev"], "Condition": "results|dataSummary|std_deviation" },
    { "ElementText": ["Devices", "Smartphone", "Valid N", "Count"], "Condition": "results|hasSmartphone|count" },
    { "ElementText": ["Devices", "Smartphone", "Smartphone: Yes", "Count"], "Condition": "results|hasSmartphone|items|T|count" },
    { "ElementText": ["Devices", "Smartphone", "Smartphone: Yes", "%"], "Condition": "results|hasSmartphone|items|T|percentage" },
    { "ElementText": ["Devices", "Smartphone", "Smartphone: No", "Count"], "Condition": "results|hasSmartphone|items|F|count" },
    { "ElementText": ["Devices", "Smartphone", "Smartphone: No", "%"], "Condition": "results|hasSmartphone|items|F|percentage" },
    { "ElementText": ["Devices", "Operating System", "Valid N", "Count"], "Condition": "results|operatingSystem|count" },
    { "ElementText": ["Devices", "Operating System", "iOS", "Count"], "Condition": "results|operatingSystem|items|iOS|count" },
    { "ElementText": ["Devices", "Operating System", "iOS", "%"], "Condition": "results|operatingSystem|items|iOS|percentage" },
    { "ElementText": ["Devices", "Operating System", "Android", "Count"], "Condition": "results|operatingSystem|items|ANDROID|count" },
    { "ElementText": ["Devices", "Operating System", "Android", "%"], "Condition": "results|operatingSystem|items|ANDROID|percentage" },
    { "ElementText": ["Devices", "Operating System", "Windows Mobile", "Count"], "Condition": "results|operatingSystem|items|WINDOWS MOBILE|count" },
    { "ElementText": ["Devices", "Operating System", "Windows Mobile", "%"], "Condition": "results|operatingSystem|items|WINDOWS MOBILE|percentage" },
    { "ElementText": ["Devices", "Operating System", "Symbian Mobile", "Count"], "Condition": "results|operatingSystem|items|SYMBIAN MOBILE|count" },
    { "ElementText": ["Devices", "Operating System", "Symbian Mobile", "%"], "Condition": "results|operatingSystem|items|SYMBIAN MOBILE|percentage" },
    { "ElementText": ["Devices", "Operating System", "Blackberry", "Count"], "Condition": "results|operatingSystem|items|BLACKBERRY|count" },
    { "ElementText": ["Devices", "Operating System", "Blackberry", "%"], "Condition": "results|operatingSystem|items|BLACKBERRY|percentage" },
    { "ElementText": ["Devices", "Operating System", "Other", "Count"], "Condition": "results|operatingSystem|items|Other|count" },
    { "ElementText": ["Devices", "Operating System", "Other", "%"], "Condition": "results|operatingSystem|items|Other|percentage" },
    { "ElementText": ["SIM", "Valid N", "Count"], "Condition": "results|simOnlyContract|count" },
    { "ElementText": ["SIM", "MBB", "Count"], "Condition": "results|hasMobileBroadband|items|T|count" },
    { "ElementText": ["SIM", "MBB", "%"], "Condition": "results|hasMobileBroadband|items|T|percentage" },
    { "ElementText": ["SIM", "SIM ONLY", "Count"], "Condition": "results|simOnlyContract|items|T|count" },
    { "ElementText": ["SIM", "SIM ONLY", "%"], "Condition": "results|simOnlyContract|items|T|percentage" }
    ]
})

dates = ['2017-05-11','2017-06-01','2017-06-08','2017-06-16']
inputJson = [ [json.load(open(varDefPath + "trend_" + d + ".json")), 
               json.load(open(varDefPath + "profileReport-" + d + ".json", "r"))] for d in dates]


tab = Table()
tab.TableTitles = ["Table 1", "Customer Profile (Active Customers)"]
tab.SuppressColumnLabels = True
for j in inputJson:
    tab.addElasticSearchColumn(j, profile, "")
from crosstabs.renderers import HTMLRenderer
html = HTMLRenderer.Render(tab, {})
display(HTML(html))